name: e2e-tests

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:

  install:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        node-version: [ 14.x ]
        browser: [ chromium, firefox ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
  
  
  install-web-components:
    strategy:
      matrix:
        os: [ macos-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    runs-on: macos-latest
    needs: install
    steps:
      - name: Build project fhjvhjjhvhjvhjirst
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set Cloud Masthead env var
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          DDS_CLOUD_MASTHEAD: true
      - name: Build storybook
        working-directory: packages/web-components
        run: yarn build-storybook


