name: e2e-tests

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  

  web-components-tests:
    runs-on: macos-latest
    needs: install-web-components
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
        os: [ macos-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: storybook-build
          path: packages/web-components/storybook-static


      # this retrieves the saved cache from the install job
      - uses: actions/cache@v2
        name: yarn-cache
        id: yarn-cache
        with:
          path: |
            **/node_modules
            /Users/runner/Library/Caches/Cypress
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - run: node_modules/cypress/bin/cypress install --force
        
      - name: 'Run e2e tests (chromium)'
        uses: cypress-io/github-action@v4
        with:
          working-directory: packages/web-components
          install: false
          command: yarn test:e2e-storybook:test:no-percy
          browser: chrome
          record: true
          parallel: true

#
